se nocp " nocompatible
se nu
se ai
se sw=4
se sts=4
se et
se ru
se is " incsearch
se hls
se nofoldenable
se completeopt-=preview
colo molokai
syntax on

let g:pymode_lint_cwindow=0
let g:pymode_repo_completion=0
let g:pymode_rope_complete_on_dot=0
